export enum InvitationLogType {
  INVITATION_CREATED = 'INVITATION_CREATED',
  INVITATION_UPDATED = 'INVITATION_UPDATED',
  INVITATION_DELETED = 'INVITATION_DELETED',
  RESPONSE_CREATED = 'RESPONSE_CREATED',
  RESPONSE_UPDATED = 'RESPONSE_UPDATED',
  RESPONSE_DELETED = 'RESPONSE_DELETED',
  VISITED = 'VISITED',
}
